#This module configures the GitHub labeler to apply the "pci" label to all pci related changes automatically requiring an independent PR review. 

pci:
- cilium/**/*
- cilium-health/**/*
- daemon/**/*
- operator/**/*
